// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


function get_files(x) {
  return x + 1 | 0;
}

var Filesystem = /* module */[/* get_files */get_files];

exports.Filesystem = Filesystem;
/* No side effect */
